<a href="https://colab.research.google.com/github/obedgar90/cofepris-BRSDM-scraper/blob/main/notebooks/visor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Visor de datos COFEPRIS BRSDM

Esta notebook ofrece una vista exploratoria rápida de los datos cargados por el proyecto `cofepris-BRSDM-scraper`.

Objetivo:
- conectarse a PostgreSQL,
- cargar la tabla de medicamentos en un DataFrame de pandas,
- inspeccionar estadísticas generales y filas de ejemplo,
- sugerir análisis visuales útiles.

In [1]:
#@title Librerías
import os

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import userdata
from sqlalchemy import create_engine, text

## Variables de entorno (SECRETS)

Si estás en colab, en el menú en secrets deben agregarse las variables de entorno **DATABASE_URL**

Por default esta variables de entorno contiene la url y el nombre de la tabla del contenedor creado en dev al ejecutar el proyecto, si utilizas otro servidor de base de datos agrégala.

In [2]:
#@title Creación del Dataframe

DATABASE_URL = userdata.get('DATABASE_URL')
TABLE_NAME = "medicamentos"

engine = create_engine(DATABASE_URL)
query = text(f"SELECT * FROM {TABLE_NAME}")

df = pd.read_sql(query, engine)

print(f"Loaded {len(df):,} rows from table '{TABLE_NAME}'.")
df.shape

Loaded 14,716 rows from table 'medicamentos'.

(14716, 29)

In [3]:
#@title Descripción estadística de los datos
df.describe(include="all").transpose()

,count,unique,top,freq,mean,min,25%,50%,75%,max
numero_de_registro,14716,14716,289M2004 SSA,1,NaN,NaN,NaN,NaN,NaN,NaN
denominacion_distintiva,14673,12970,AMOXIL,8,NaN,NaN,NaN,NaN,NaN,NaN
fecha_expedicion_vigencia,14638,7776,1 DE ENERO DE 1968 / 24 DE FEBRERO DE 2010,255,NaN,NaN,NaN,NaN,NaN,NaN
fecha_expedicion_vigencia_prorroga,8998,2476,18 DE ABRIL DE 2022 / 18 DE ABRIL DE 2027,46,NaN,NaN,NaN,NaN,NaN,NaN
estado,14716,3,VIGENTE,9947,NaN,NaN,NaN,NaN,NaN,NaN
forma_farmaceutica,14627,66,TABLETA,5052,NaN,NaN,NaN,NaN,NaN,NaN
indicaciones_terapeuticas,14572,7884,ANTIHIPERTENSIVO.,171,NaN,NaN,NaN,NaN,NaN,NaN
contra_indicaciones,14512,11576,HIPERSENSIBILIDAD A LOS COMPONENTES DE LA FÓRM...,991,NaN,NaN,NaN,NaN,NaN,NaN
vida_util,10521,945,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",5709,NaN,NaN,NaN,NaN,NaN,NaN
fraccion,14320,6,IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,11383,NaN,NaN,NaN,NaN,NaN,NaN
denominacion_generica,14716,3578,/ / /,820,NaN,NaN,NaN,NaN,NaN,NaN
vista_administracion,13613,44,ORAL,8626,NaN,NaN,NaN,NaN,NaN,NaN
tipo_medicamento,13959,8,GENÉRICO,8342,NaN,NaN,NaN,NaN,NaN,NaN
presentacion,14200,12653,FRASCO CON 100 TABLETAS.,47,NaN,NaN,NaN,NaN,NaN,NaN
cantidad,13012,9459,KETOCONAZOL 2.000 G,25,NaN,NaN,NaN,NaN,NaN,NaN
sistema_organico,10953,15,A SISTEMA DIGESTIVO Y METABOLISMO,1712,NaN,NaN,NaN,NaN,NaN,NaN
grupo_farmacologico,10915,88,J01 ANTIBACTERIANOS PARA USO SISTÉMICO,746,NaN,NaN,NaN,NaN,NaN,NaN
subgrupo_farmacologico,10910,239,M01A PRODUCTOS ANTIINFLAMATORIOS Y ANTIRREUMÁT...,522,NaN,NaN,NaN,NaN,NaN,NaN
subgrupo_quimico,10791,659,N02BE ANILIDAS,203,NaN,NaN,NaN,NaN,NaN,NaN
sustancia_quimica,10289,1929,N02BE01 PARACETAMOL.,149,NaN,NaN,NaN,NaN,NaN,NaN
titular,14558,1418,"LABORATORIOS PISA, S.A. DE C.V.",336,NaN,NaN,NaN,NaN,NaN,NaN
domicilio,14558,4095,"BLVD. GARCÍA MORALES KM 6.5.,EL LLANO, C.P. 83...",142,NaN,NaN,NaN,NaN,NaN,NaN
fabricantes_medicamentos,14206,6251,"GRIMANN, S.A. DE C.V. ,CIRCUITO NEMESIO DIEZ R...",130,NaN,NaN,NaN,NaN,NaN,NaN
fabricantes_farmacos,12041,9823,"BIOLOGISCHE HEILMITTEL HEEL GMBH ,",52,NaN,NaN,NaN,NaN,NaN,NaN
acondicionado_por,8414,2680,"PRODUCTOS MAVER, S.A. DE C.V., OLEODUCTO NO. 2...",74,NaN,NaN,NaN,NaN,NaN,NaN
acondicionado_extranjero,4145,2837,"BIOLOGISCHE HEILMITTEL HEEL GMBH ,DR.-RECKEWEG...",103,NaN,NaN,NaN,NaN,NaN,NaN
distribuidores,12395,4595,"RUBIO PHARMA Y ASOCIADOS, S.A. DE C.V. , BLVD....",169,NaN,NaN,NaN,NaN,NaN,NaN
unidad_farmaco_vigilancia,2365,1149,"AUROVIDA FARMACÉUTICA S.A. DE C.V. , RÍO TÍBER...",39,NaN,NaN,NaN,NaN,NaN,NaN
fecha_emision,14650,NaN,NaN,NaN,2010-09-23 02:28:15.071672320,1900-01-01 20:00:00,2005-01-31 15:30:00,2013-07-08 15:00:00,2017-10-13 15:00:00,2026-05-07 09:00:00

In [4]:
#@title Muestra de datos
df.head(10)

,numero_de_registro,denominacion_distintiva,fecha_expedicion_vigencia,fecha_expedicion_vigencia_prorroga,estado,forma_farmaceutica,indicaciones_terapeuticas,contra_indicaciones,vida_util,fraccion,...,sustancia_quimica,titular,domicilio,fabricantes_medicamentos,fabricantes_farmacos,acondicionado_por,acondicionado_extranjero,distribuidores,unidad_farmaco_vigilancia,fecha_emision
0,363M2018 SSA,ROLODIQUIM FST,28 DE NOVIEMBRE DE 2018 / 28 DE NOVIEMBRE DE 2023,8 DE MAYO DE 2023 / 8 DE MAYO DE 2028,VIGENTE,TABLETA,ANALGÉSICO NO NARCÓTICO.,HIPERSENSIBILIDAD AL FÁRMACO O A LOS COMPONENT...,24 MESES DEBIENDO EXPRESAR EL AÑO CON NÚMERO Y...,IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,M01AB15 KETOROLACO,"QUIMICA Y FARMACIA, S.A. DE C.V.","BOULEVARD INDUSTRIA AUTOMOTRIZ 3045, FRACC. II...","QUÍMICA Y FARMACIA, S. A. DE C. V. ,BLVD. IND....","SYMED LABORATORIES LIMITED. ,UNIT II, PLOT NO....","PERRIGO DE MEXICO, S.A. DE C.V., AV. INDUSTRIA...",None,"QUIMICA Y FARMACIA, S.A. DE C.V. , BLVD. IND. ...",None,2018-11-29 04:00:00
1,004M2020 SSA,ELIFORE,17 DE ENERO DE 2020 / 17 DE ENERO DE 2025,30 DE AGOSTO DE 2024 / 30 DE AGOSTO DE 2029,CANCELADO,TABLETA,TRASTORNO DEPRESIVO MAYOR Y SÍNTOMAS VASOMOTOR...,HIPERSENSIBILIDAD A LOS COMPONENTES DE LA FÓRM...,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,N06AX23 DESVENLAFAXINA,PHARMACIA & UPJOHN COMPANY LLC,"7000 PORTAGE ROAD, KALAMAZOO, MI 49001, ESTADO...","PFIZER IRELAND PHARMACEUTICALS. ,LITTLE CONNEL...","PFIZER ASIA PACIFIC PTE LTD ,31 TUAS SOUTH AVE...","PFIZER, S.A. DE C.V., CARRETERA MEXICO-TOLUCA ...",None,"PFIZER, S.A. DE C.V. , CARRETERA MEXICO-TOLUCA...","PFIZER, S.A. DE C.V. , CARRETERA MEXICO-TOLUCA...",2020-01-17 10:00:00
2,305M2018 SSA,THERAFLU THERAPILLIS,8 DE NOVIEMBRE DE 2018 / 9 DE AGOSTO DE 2024,15 DE MARZO DE 2024 / 15 DE MARZO DE 2029,VIGENTE,TABLETA,AUXILIAR EN EL TRATAMIENTO SINTOMÁTICO DEL RES...,HIPERSENSIBILIDAD A LOS COMPONENTES DE LA FORM...,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",VI. MEDICAMENTOS QUE PARA ADQUIRIRSE NO REQUIE...,...,"R01BA53 FENILEFRINA, COMBINATIONS","GLAXOSMITHKLINE CONSUMER HEALTHCARE MEXICO, S....","CALLE 21-E 104 NA,CIVAC, JIUTEPEC, MORELOS, M...","HALEONPANAMÁ, S.A. ,CORREGIMIENTO DE JUAN DÍAZ...","DIVI´S LABORATORIES LIMITED ,UNIT-2, CHIPPADA...",None,"GLAXOSMITHKLINE PANAMÁ, S.A ,URBANIZACIÓN INDU...","GLAXOSMITHKLINE CONSUMER HEALTHCARE MEXICO, S....",None,2018-11-09 04:00:00
3,293M2018 SSA,ENDOESTAT,15 DE OCTUBRE DE 2018 / 15 DE OCTUBRE DE 2023,26 DE JUNIO DE 2023 / 26 DE JUNIO DE 2028,VIGENTE,SOLUCIÓN,ANTIEPILÉPTICO,"HIPERSENSIBILIDAD AL LEVETIRACETAM, OTROS DERI...","24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,N03AX14 LEVETIRACETAM,NUCITEC S.A DE C.V,"AV. JURICA 116,PARQUE INDUSTRIAL QUERETARO, C....","NUCITEC, S.A. DE C.V. ,AV. JURIDICA NO. 116, ...","LUPIN LIMITED. ,T-142, TARAPUR, VIA- BOISAR, T...","NUCITEC S.A DE C.V, AV. JURICA 116, PARQUE IND...",None,"NUCITEC S.A DE C.V , AV. JURICA 116, PARQUE IN...",None,2018-10-15 19:00:00
4,254M2018 SSA,SINBIOTREX,26 DE SEPTIEMBRE DE 2018 / 26 DE SEPTIEMBRE DE...,18 DE ABRIL DE 2023 / 18 DE ABRIL DE 2028,VIGENTE,TABLETA,LAXANTE.,HIPERSENSIBILIDAD A LOS COMPONENTES DE LA FÓRM...,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",VI. MEDICAMENTOS QUE PARA ADQUIRIRSE NO REQUIE...,...,A06AB06 GLICÓSIDOS DE SENNA.,"LABORATORIOS SCHOEN, S.A. DE C.V.","RÍO TIZAPÁN NO. 1599,ATLAS, C.P. 44767, GUADA...","LABORATORIOS SCHOEN, S.A. DE C.V. ,RÍO TIZAPÁN...","ALCHEM INTERNATIONAL PVT. LIMITED ,SP-2-5, RII...","LABORATORIOS SCHOEN, S.A. DE C.V., RIO TIZAPAN...",None,"LABORATORIOS SCHOEN, S.A. DE C.V. , RIO TIZAPA...",None,2018-09-26 17:00:00
5,377M2018 SSA,NUWIQ,19 DE DICIEMBRE DE 2018 / 28 DE AGOSTO DE 2028,28 DE AGOSTO DE 2023 / 28 DE AGOSTO DE 2028,VIGENTE,SOLUCIÓN,TRATAMIENTO Y PROFILAXIS DE LA HEMORRAGIA EN P...,HIPERSENSIBILIDAD AL PRINCIPIO ACTIVO O A CUAL...,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,B02BD02 FACTOR VIII DE COAGULACIÓN.,"OCTAPHARMA, S.A. DE C.V.","CALZADA MÉXICO TACUBA 1419 1419,ARGENTINA PONI...","OCTAPHARMA AB ,LARS FORSSELLS GATA 23, STOCKHO...","OCTAPHARMA AB ,LARS FORSSELLS GATA 23, STOCKHO...",None,"OCTAPHARMA AB ,LARS FORSSELLS GATA 23, STOCKHO...","OCTAPHARMA, S.A. DE C.V. , CALZADA MÉXICO TACU...",None,2018-12-19 20:00:00
6,352M2018 SSA,MINABRON,22 DE NOVIEMBRE DE 2018 / 22 DE NOVIEMBRE DE 2023,19 DE JUNIO DE 2023 / 19 DE JUNIO DE 2028,VIGENTE,TABLETA.,TRATAMIENTO AGUDO Y CRÓNICO DE LOS SIGNOS Y SÍ...,HIPERSENSIBILIDAD A CUALQUIERA DE LOS COMPONEN...,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,M01AH05 ETORICOXIB,NUCITEC S.A. DE C.V,"COMERCIANTES NO. 18 NAVE 3,PEÑUELAS, C.P. 7614...","NUCITEC, S.A. DE C.V. ,AV. JURICA NO. 116, PAR...",ALEMBIC PHARMACEUTICALS LIMITED (API DIVISION ...,"NUCITEC, S. A. DE C. V., AV. JURICA 116, PARQU...",None,"NUCITEC, S. A. DE C. V. , AV. JURICA 116, PARQ...",None,2018-11-23 04:00:00
7,366M2018 SSA,WIXEG,30 DE NOVIEMBRE DE 2018 / 30 DE NOVIEMBRE DE 2023,28 DE FEBRERO DE 2023 / 28 DE FEBRERO DE 2028,VIGENTE,TABLETA.,ANTIVIRAL. PREVENCION DE INFECCIONES POR CITOM...,HIPERSENSIBILIDAD A CUALQUIERA DE LOS COMPONEN...,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,"J05AB01 NUCLEÓSIDOS Y NUCLEÓTIDOS, EXCL. INH...","LABORATORIOS CORNE, S.A. DE C.V.","OCAMPO NO.167 - A,LAS ENCINAS, C.P. 66050, GE...","LABORATORIOS CORNE, S.A. DE C.V. ,OCAMPO NO. 1...","ZHEJIANG CHARIOTEER PHARMACEUTICAL CO. LTD. ,T...","LABORATORIOS CORNE, S.A. DE C.V., OCAMPO. NO.1...",None,"LABORATORIOS CORNE S.A. DE C.V. , ORIENTE 171 ...",None,2018-11-30 16:00:00
8,240M2018 SSA,LYSOMUCILSNI,27 DE SEPTIEMBRE DE 2018 / 27 DE SEPTIEMBRE DE...,1 DE JUNIO DE 2023 / 1 DE JUNIO DE 2028,VIGENTE,SOLUCIÓN,MUCOLÍTICO PARA EL TRATAMIENTO DE CONDICIONES ...,HIPERSENSIBILIDAD A LOS COMPONENTES DE LA FÓRM...,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,R05CB01 ACETILCISTEÍNA,"VIDRIO TECNICO DE COLOMBIA S.A. VITECO S.A.,","TRANSVERSAL 20A NO. 4A-81, BOGOTÁ D.C., COLOMB...",VIDRIO TÉCNICO DE COLOMBIA S.A. (VITECO S.A.) ...,"F.I.S. FABBRICA ITALIANA SINTETICI S.P.A. ,VIA...",None,"VIDRIO TECNICO DE COLOMBIA S.A. VITECO S.A., ,...","LABORATORIOS CONCORDIA, S. A. DE C. V. , CARRE...","LABORATORIOS CONCORDIA,S.A. D C.V. , AV.EJERCI...",2018-09-27 05:00:00
9,79835 SSA,NARCANTI,1 DE ENERO DE 1968 / 24 DE FEBRERO DE 2010,None,REVOCADO,SOLUCIÓN,"ANTAGONISTA OPIOIDE, PARA REVERTIR LOS EFECTOS...","HIPERSENSIBILIDAD AL CLORHIDRATO DE NALOXONA, ...",None,IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,...,V03AB15 NALOXONA,"BRISTOL MYERS SQUIBB DE MÉXICO, S. DE R.L. DE ...","CALZ. DE TLALPAN NO. 2996,EJIDO DE SANTA URSUL...",None,None,None,None,None,None,1968-01-01 08:00:00

In [5]:
#@title Limpieza del Dataframe
# Separación de fechas de vigencia y prorroga
df[['Fecha_Expedición', 'Fecha_Vigencia']]=df['fecha_expedicion_vigencia'].str.split('/', expand=True)
df[['Fecha_Expedición_Prorroga', 'Fecha_Vigencia_Prorroga']] = df['fecha_expedicion_vigencia_prorroga'].str.split('/', expand=True)

# Separación fabricante del medicamento
df['Fabricante_Nombre'] = df['fabricantes_medicamentos'].str.split(' ,').str[0]
df['Fabricante_Pais'] = df['fabricantes_medicamentos'].str.split(', ').str[-1]

In [6]:
df.describe(include="all").transpose()

,count,unique,top,freq,mean,min,25%,50%,75%,max
numero_de_registro,14716,14716,289M2004 SSA,1,NaN,NaN,NaN,NaN,NaN,NaN
denominacion_distintiva,14673,12970,AMOXIL,8,NaN,NaN,NaN,NaN,NaN,NaN
fecha_expedicion_vigencia,14638,7776,1 DE ENERO DE 1968 / 24 DE FEBRERO DE 2010,255,NaN,NaN,NaN,NaN,NaN,NaN
fecha_expedicion_vigencia_prorroga,8998,2476,18 DE ABRIL DE 2022 / 18 DE ABRIL DE 2027,46,NaN,NaN,NaN,NaN,NaN,NaN
estado,14716,3,VIGENTE,9947,NaN,NaN,NaN,NaN,NaN,NaN
forma_farmaceutica,14627,66,TABLETA,5052,NaN,NaN,NaN,NaN,NaN,NaN
indicaciones_terapeuticas,14572,7884,ANTIHIPERTENSIVO.,171,NaN,NaN,NaN,NaN,NaN,NaN
contra_indicaciones,14512,11576,HIPERSENSIBILIDAD A LOS COMPONENTES DE LA FÓRM...,991,NaN,NaN,NaN,NaN,NaN,NaN
vida_util,10521,945,"24 MESES, DEBIENDO EXPRESAR EL AÑO CON NÚMERO ...",5709,NaN,NaN,NaN,NaN,NaN,NaN
fraccion,14320,6,IV. MEDICAMENTOS QUE PARA ADQUIRIRSE REQUIERE ...,11383,NaN,NaN,NaN,NaN,NaN,NaN
denominacion_generica,14716,3578,/ / /,820,NaN,NaN,NaN,NaN,NaN,NaN
vista_administracion,13613,44,ORAL,8626,NaN,NaN,NaN,NaN,NaN,NaN
tipo_medicamento,13959,8,GENÉRICO,8342,NaN,NaN,NaN,NaN,NaN,NaN
presentacion,14200,12653,FRASCO CON 100 TABLETAS.,47,NaN,NaN,NaN,NaN,NaN,NaN
cantidad,13012,9459,KETOCONAZOL 2.000 G,25,NaN,NaN,NaN,NaN,NaN,NaN
sistema_organico,10953,15,A SISTEMA DIGESTIVO Y METABOLISMO,1712,NaN,NaN,NaN,NaN,NaN,NaN
grupo_farmacologico,10915,88,J01 ANTIBACTERIANOS PARA USO SISTÉMICO,746,NaN,NaN,NaN,NaN,NaN,NaN
subgrupo_farmacologico,10910,239,M01A PRODUCTOS ANTIINFLAMATORIOS Y ANTIRREUMÁT...,522,NaN,NaN,NaN,NaN,NaN,NaN
subgrupo_quimico,10791,659,N02BE ANILIDAS,203,NaN,NaN,NaN,NaN,NaN,NaN
sustancia_quimica,10289,1929,N02BE01 PARACETAMOL.,149,NaN,NaN,NaN,NaN,NaN,NaN
titular,14558,1418,"LABORATORIOS PISA, S.A. DE C.V.",336,NaN,NaN,NaN,NaN,NaN,NaN
domicilio,14558,4095,"BLVD. GARCÍA MORALES KM 6.5.,EL LLANO, C.P. 83...",142,NaN,NaN,NaN,NaN,NaN,NaN
fabricantes_medicamentos,14206,6251,"GRIMANN, S.A. DE C.V. ,CIRCUITO NEMESIO DIEZ R...",130,NaN,NaN,NaN,NaN,NaN,NaN
fabricantes_farmacos,12041,9823,"BIOLOGISCHE HEILMITTEL HEEL GMBH ,",52,NaN,NaN,NaN,NaN,NaN,NaN
acondicionado_por,8414,2680,"PRODUCTOS MAVER, S.A. DE C.V., OLEODUCTO NO. 2...",74,NaN,NaN,NaN,NaN,NaN,NaN
acondicionado_extranjero,4145,2837,"BIOLOGISCHE HEILMITTEL HEEL GMBH ,DR.-RECKEWEG...",103,NaN,NaN,NaN,NaN,NaN,NaN
distribuidores,12395,4595,"RUBIO PHARMA Y ASOCIADOS, S.A. DE C.V. , BLVD....",169,NaN,NaN,NaN,NaN,NaN,NaN
unidad_farmaco_vigilancia,2365,1149,"AUROVIDA FARMACÉUTICA S.A. DE C.V. , RÍO TÍBER...",39,NaN,NaN,NaN,NaN,NaN,NaN
fecha_emision,14650,NaN,NaN,NaN,2010-09-23 02:28:15.071672320,1900-01-01 20:00:00,2005-01-31 15:30:00,2013-07-08 15:00:00,2017-10-13 15:00:00,2026-05-07 09:00:00
Fecha_Expedición,14638,5409,1 DE ENERO DE 1968,271,NaN,NaN,NaN,NaN,NaN,NaN
Fecha_Vigencia,14638,4346,25 DE FEBRERO DE 2010,1635,NaN,NaN,NaN,NaN,NaN,NaN
Fecha_Expedición_Prorroga,8998,2110,18 DE ABRIL DE 2022,46,NaN,NaN,NaN,NaN,NaN,NaN
Fecha_Vigencia_Prorroga,8998,2221,18 DE ABRIL DE 2027,47,NaN,NaN,NaN,NaN,NaN,NaN
Fabricante_Nombre,14206,2240,"LABORATORIOS PISA, S.A. DE C.V.",398,NaN,NaN,NaN,NaN,NaN,NaN
Fabricante_Pais,14206,244,MÉXICO,8884,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
#@title Dataframe Limpio
Registros_Sanitarios= df[['numero_de_registro','Fecha_Expedición','Fecha_Vigencia','Fecha_Expedición_Prorroga','Fecha_Vigencia_Prorroga','denominacion_distintiva','tipo_medicamento','titular','domicilio','Fabricante_Nombre','Fabricante_Pais']]

## Gráficas sugeridas para el análisis

1. **Principales sustancias activas** (`sustancia_quimica`): gráfica de barras horizontal con los 20 valores más frecuentes.
2. **Distribución por estatus** (`estado`): gráfica de barras para comparar `VIGENTE`, `CANCELADO`, etc.
3. **Desglose por grupo terapéutico** (`grupo_farmacologico`): treemap o gráfica de barras.
4. **Tendencia de emisión en el tiempo** (`fecha_emision`): línea mensual después de parsear fechas.
5. **Titulares más frecuentes** (`titular`): top 15 entidades por número de registros.
6. **Mezcla de presentación / forma farmacéutica** (`presentacion`, `forma_farmaceutica`): barras apiladas o mapa de calor.

Si hace falta, agrega una celda de preprocesamiento para parsear fechas y normalizar valores faltantes antes de graficar.

## Preprocesamiento de Datos

Antes de graficar, realizaremos un preprocesamiento de las columnas relevantes:
- Convertir `fecha_emision` a tipo datetime.
- Llenar valores nulos en columnas categóricas con 'Desconocido' para asegurar que aparezcan en las gráficas, o simplemente eliminar nulos antes del conteo.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Convertir 'fecha_emision' a datetime, forzando errores a NaT
df['fecha_emision'] = pd.to_datetime(df['fecha_emision'], errors='coerce')

# Rellenar NaNs en columnas categóricas importantes con 'Desconocido' para la visualización
# O simplemente eliminar NaNs para el conteo de frecuencias
for col in ['sustancia_quimica', 'estado', 'grupo_farmacologico', 'titular', 'presentacion', 'forma_farmaceutica']:
    if col in df.columns:
        # For frequency counts, it's often better to drop NaNs or count them explicitly
        # For now, we'll just ensure they are of the correct type if not already.
        # If we fill, it would be df[col] = df[col].fillna('Desconocido')
        pass

print("Preprocesamiento de fechas y manejo básico de nulos completado.")

---

## 1. Principales sustancias activas (`sustancia_quimica`)
Gráfica de barras horizontal con los 20 valores más frecuentes.

In [ ]:
plt.figure(figsize=(12, 8))
# Contar las frecuencias y tomar los top 20, excluyendo NaNs
top_sustancias = df['sustancia_quimica'].value_counts().nlargest(20)
sns.barplot(x=top_sustancias.values, y=top_sustancias.index, palette='viridis')
plt.title('Top 20 Sustancias Químicas Más Frecuentes')
plt.xlabel('Número de Registros')
plt.ylabel('Sustancia Química')
plt.tight_layout()
plt.show()

---

## 2. Distribución por estatus (`estado`)
Gráfica de barras para comparar `VIGENTE`, `CANCELADO`, etc.

In [ ]:
plt.figure(figsize=(10, 6))
sns.countplot(x='estado', data=df, palette='rocket', order=df['estado'].value_counts().index)
plt.title('Distribución de Registros por Estado')
plt.xlabel('Estado')
plt.ylabel('Número de Registros')
plt.tight_layout()
plt.show()

---

## 3. Desglose por grupo terapéutico (`grupo_farmacologico`)
Gráfica de barras de los grupos farmacológicos más frecuentes.

In [ ]:
plt.figure(figsize=(12, 8))
# Contar las frecuencias y tomar los top 20, excluyendo NaNs
top_grupos = df['grupo_farmacologico'].value_counts().nlargest(20)
sns.barplot(x=top_grupos.values, y=top_grupos.index, palette='mako')
plt.title('Top 20 Grupos Farmacológicos Más Frecuentes')
plt.xlabel('Número de Registros')
plt.ylabel('Grupo Farmacológico')
plt.tight_layout()
plt.show()

---

## 4. Tendencia de emisión en el tiempo (`fecha_emision`)
Línea mensual después de parsear fechas.

In [ ]:
plt.figure(figsize=(15, 7))
# Agrupar por mes y contar registros, eliminando NaNs de fecha_emision
df_time_series = df.set_index('fecha_emision').resample('M').size().reset_index(name='count')

sns.lineplot(x='fecha_emision', y='count', data=df_time_series)
plt.title('Tendencia Mensual de Emisión de Registros')
plt.xlabel('Fecha de Emisión')
plt.ylabel('Número de Registros')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

---

## 5. Titulares más frecuentes (`titular`)
Top 15 entidades por número de registros.

In [ ]:
plt.figure(figsize=(12, 8))
# Contar las frecuencias y tomar los top 15, excluyendo NaNs
top_titulares = df['titular'].value_counts().nlargest(15)
sns.barplot(x=top_titulares.values, y=top_titulares.index, palette='cubehelix')
plt.title('Top 15 Titulares Más Frecuentes')
plt.xlabel('Número de Registros')
plt.ylabel('Titular')
plt.tight_layout()
plt.show()